#!/usr/bin/env bash
# Display fizz, buzz ,fizzbuzz or a no. for no. between 1 and 100 inclusive.
i=1
while ((i <= 100)); do
	if ((((i % 3)) == 0)) && ((((i % 5)) == 0)); then
		echo "FizzBuzz"
	elif ((((i % 3)) == 0)); then
		echo "Fizz"
	elif ((((i % 5)) == 0)); then
		echo "Buzz"
	else
		echo "$i"
	fi
	((i++))
done
