#!/usr/bin/env bash
# Display Best School 8 times in a 10 while loop. The other 2 loops display bad luck and good luck on the 4th and 8th loop respectively.
i=1
while ((i <= 10)); do
	if ((i == 4)); then
		echo "bad luck"
	elif ((i == 8)); then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
