#!/usr/bin/env bash
# Display no. 1-20, bad luck from China, Japan, Italy for no. 4, 9, 17.
i=1
while ((i <= 20)); do
	echo "$i"
	case "$i" in
		4)
			echo "bad luck from China"
		9)
			echo "bad luck from Japan"
		17)
			echo "bad luck from Italy"
	esac
	((i++))
done
