#!/usr/bin/env bash
# This file shows if a file school exists or not, if it is empty or not and if it is a regular file.
if [ -e school ]; then
	echo "school file exists"
	if [ -s school ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f school ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
